name: 'Auditmation SBOM Recorder'
description: 'Creates a pipeline and uploads SBOM files to Auditmation'
inputs:
  api-key:
    description: 'Auditmation API key'
    required: true
  org-id:
    description: 'Auditmation Org ID'
    required: true
  boundary-id:
    description: 'Boundary ID, required if more than one boundary exists'
    required: false
    default: ''
  url:
    description: 'Auditmation API key'
    required: true
    default: 'https://nf.auditmation.io'
  package:
    description: 'NPM package to upload the SBOM from (@scope/package-name@version)'
    required: true
  file-path:
    description: 'Path inside the package to the SBOM file'
    required: true
    default: bom.json
  product-id:
    description: ID of the product to place the pipeline in
    default: '23cf2909-5c5e-5546-be5f-7f167d1f1c16'
runs:
  using: 'node24'
  main: 'dist/index.js'
